version: '3.8'

services:
  web:
    build: .
    ports:
      - "8765:8765"
    volumes:
      - .:/app
      - ./static/logos:/app/static/logos
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped 