version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app  # Mount the entire project directory for live code changes
      - ./static:/app/static
      - ./uploads:/app/uploads
      - invoice_db_data:/app/db
      - invoice_migrations_data:/app/migrations
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SECRET_KEY=dev-secret-key
      - DATABASE_URL=sqlite:////app/db/invoice_gen.db
      - SCRIPT_NAME=/invoice
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - invoice_network
    command: flask run --host=0.0.0.0 --port=8080

networks:
  invoice_network:
    driver: bridge

volumes:
  invoice_db_data:
    driver: local
  invoice_migrations_data:
    driver: local 