version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      # Mount the static/logos directory to persist uploaded logos
      # This is important so that uploaded logos are not lost when the container restarts.
      # We'll create a local directory named 'user_logos' to store these.
      - ./user_logos:/app/static/logos
      - ./invoice_gen.db:/app/invoice_gen.db
    environment:
      # Ensure Flask and Gunicorn use the correct settings
      - FLASK_APP=wsgi.py
      - FLASK_ENV=production
      - SECRET_KEY=your-secure-secret-key-here
      - DATABASE_URL=sqlite:///invoice_gen.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/static/css/style.css"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Optional: Define a volume for persistent data if not mounting a host directory
# volumes:
#   user_logos_data:
