version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      # Mount the static/logos directory to persist uploaded logos
      # This is important so that uploaded logos are not lost when the container restarts.
      # We'll create a local directory named 'user_logos' to store these.
      - ./invoice/static/user_logos:/app/invoice/static/user_logos
      # Use a named volume for uploads
      - uploads_data:/app/static/uploads
      - invoice_db_data:/app/db
    environment:
      # Ensure Flask and Gunicorn use the correct settings
      - FLASK_APP=wsgi.py
      - FLASK_ENV=production
      - SECRET_KEY=your-secure-secret-key-here
      - DATABASE_URL=sqlite:///db/invoice_gen.db
      - SCRIPT_NAME=/invoice
    restart: unless-stopped
    networks:
      - invoice_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/static/css/style.css"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: gunicorn --bind 0.0.0.0:8080 app:app

networks:
  invoice_network:
    driver: bridge

volumes:
  invoice_db_data:
  uploads_data:

# Optional: Define a volume for persistent data if not mounting a host directory
# volumes:
#   user_logos_data:
