version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./static:/app/static
      - ./uploads:/app/uploads
      - invoice_db_data:/app/db
      - invoice_migrations_data:/app/migrations
    environment:
      - FLASK_APP=app_factory.py
      - FLASK_ENV=${FLASK_ENV:-production}
      - SECRET_KEY=dev-key-please-change-in-production
      - DATABASE_URL=sqlite:////app/db/invoice_gen.db
      - SCRIPT_NAME=/invoice
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - invoice_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/static/style.css"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  invoice_network:
    driver: bridge

volumes:
  invoice_db_data:
    driver: local
  invoice_migrations_data:
    driver: local

# Optional: Define a volume for persistent data if not mounting a host directory
# volumes:
#   user_logos_data:
